language: generic
sudo: required
services:
  - docker
before_install:
  - docker build  -t bhaggi007/doceker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true bhaggi007/docker-react npm run test